
version: '3.8'

services:
  #BACKEND
  backend:
    build: ./paint-backend
    container_name: paint-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./paint-backend/.env
    networks:
      - paint-network

  #FRONTEND
  frontend:
    build: ./paint-frontend
    container_name: paint-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - ./paint-frontend/.env
    depends_on:
      - backend
    networks:
      - paint-network

# NETWORKS
networks:
  paint-network:
    driver: bridge
